### PR TITLE
A couple of fixes and a new graph

### PR DESCRIPTION
**Pull request by lorf**
This fixes changed units of some metrics in node_exporter 0.17 in couple of places.

Also added a Disk Length Queue graph which is helpful in disk I/O troubleshooting.

### CODE REVIEW

**Comment by knutemann** [comment]
Hi,

Thanks for the PR! 

I've been trying to maintain support for older versions of node exporter. I think we should still try to make the dashboard work well for versions back to 0.13. You mention changes between 0.16 and 0.17. I do not have the opportunity to verify that this will work for 0.13, 0.16 and 0.17. Could you give confirmation and/or add support for the three mentioned versions for your changes?

The added graph should definitively be added to the dashboard.


-- 
Knut

**Comment by lorf** [comment]
The fixes only change calculations which include metrics exported by 0.17
and doesn't touch calculations related to "older" metrics, so they should
not introduce any regressions, but only fix blind translation from "old" to
"new" metrics.

The queue length graph uses node_disk_io_now metric which is available in
all mentioned versions, here is 0.13:
https://github.com/prometheus/node_exporter/blob/v0.13.0/collector/diskstats_linux.go#L135

I would check it live if You like.

чт, 30 авг. 2018 г. в 18:36, Knut Ytterhaug <notifications@github.com>:

**Comment by lorf** [comment]
OK, here it is: https://snapshot.raintank.io/dashboard/snapshot/0m3JiAq9s5eSfy0MSR03UqDkAf20EV1d?orgId=2

This is generated by running 3 versions of node_exporter in docker and generating some disk activity on localhost. All graphs seem to match, except disk queue length graphs, which is explainable - this is a gauge that changes quickly, and the value depends highly on the exact moment it was taken.

Btw, I added a docker-compose.yml for running prometheus, 3 versions of node_exporter and grafana with node-exporter dashboard imported here: https://github.com/lorf/grafana-dashboards/tree/master/node-exporter-server-metrics/node-exporter-test , will make a pull request if You like.

**Comment by lorf** [comment]
The last commit fixes this:

**Pull request merged**
